#!/bin/bash

#Create user
#useradd -m dmyrhorodskyi
#usermod -aG sudo dmyrhorodskyi
#echo dmyrhorodskyi:secret | chpasswd

#Add user to sudoers
#echo "+ : ALL : ALL" > /etc/security/access.conf
#echo "dmyrhorodskyi ALL = (root) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/dmyrhorodskyi
#sudo chmod 0440 /etc/sudoers.d/dmyrhorodskyi

#Add ssh key from ubuntu user to created user
#mkdir /home/dmyrhorodskyi/.ssh/
#cp /home/ubuntu/.ssh/authorized_keys /home/dmyrhorodskyi/.ssh/
#chmod 644 /home/dmyrhorodskyi/.ssh/authorized_keys

#Add Mirantis DNS
echo "nameserver 172.18.208.44" >> /etc/resolvconf/resolv.conf.d/head
service resolvconf restart

#Install docker
apt-get update
apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io docker-compose -y


