#!/bin/bash

#Create user
#useradd -m dmyrhorodskyi
#usermod -aG sudo dmyrhorodskyi
#echo dmyrhorodskyi:secret | chpasswd

#Add user to sudoers
#echo "+ : ALL : ALL" > /etc/security/access.conf
#echo "dmyrhorodskyi ALL = (root) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/dmyrhorodskyi
#sudo chmod 0440 /etc/sudoers.d/dmyrhorodskyi

#Add ssh key from ubuntu user to created user
#mkdir /home/dmyrhorodskyi/.ssh/
#cp /home/ubuntu/.ssh/authorized_keys /home/dmyrhorodskyi/.ssh/
#chmod 644 /home/dmyrhorodskyi/.ssh/authorized_keys

#Add Mirantis DNS
echo "nameserver 172.18.208.44" >> /etc/resolvconf/resolv.conf.d/head
service resolvconf restart

#Install docker
apt-get update
apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io docker-compose -y

#Downlad and instal gerrit
cat << EOF > /etc/docker/daemon.json
{
  "bip": "10.159.169.1/16"
}
EOF
service docker restart

git clone https://github.com/MirgDenis/gerrit-codereview.git /home/ubuntu/Downloads
mkdir -p /home/ubuntu/Downloads/gerrit-codereview/gerrit/etc \
/home/ubuntu/Downloads/gerrit-codereview/gerrit/git /home/ubuntu/Downloads/gerrit-codereview/gerrit/index \
/home/ubuntu/Downloads/gerrit-codereview/gerrit/cache /home/ubuntu/Downloads/gerrit-codereview/postgres \
/home/ubuntu/Downloads/gerrit-codereview/ldap/var /home/ubuntu/Downloads/gerrit-codereview/ldap/etc

cp /home/ubuntu/Downloads/gerrit-codereview/files/gerrit.config /home/ubuntu/Downloads/gerrit-codereview/gerrit/etc/gerrit.config
cp /home/ubuntu/Downloads/gerrit-codereview/files/secure.config /home/ubuntu/Downloads/gerrit-codereview/gerrit/etc/secure.config

chown -R 1000:1000 /home/ubuntu/Downloads/gerrit-codereview/gerrit

sed -i 's|#entrypoint|entrypoint|' /home/dmyrhorodskyi/Downloads/gerrit-codereview/files/docker-compose.yml
docker-compose up -d postgres
sleep 30
docker-compose up gerrit
sed -i 's|entrypoint|#entrypoint|' /home/dmyrhorodskyi/Downloads/gerrit-codereview/files/docker-compose.yml
docker-compose up -d

